#pragma once
#ifndef __ENUM_H__
#define __ENUM_H__

enum OBJID{BACKGROUND, PLAYER, MONSTER, OBJID_END};
enum TEXTYPE {SINGLE, MULTI, TEXTYPE_END};
enum SCENE {TITLE, GAME, SCENE_END};
enum OBJSTATE {NO_EVENT,DEAD, OBJSTATE_END};

enum class COMPONENTID { TRANSFORM, CONTROLLER, RENDER, COLLISION, END };

#endif //__ENUM_H__